//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z3_4_Sadyrin
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdIzm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EdIzm()
        {
            this.StroyMaterial = new HashSet<StroyMaterial>();
        }
    
        public int StroyMaterialID { get; set; }
        public string EdIzm1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StroyMaterial> StroyMaterial { get; set; }
    }
}
