//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z3_4_Sadyrin
{
    using System;
    using System.Collections.Generic;
    
    public partial class StroyMaterial
    {
        public int ID { get; set; }
        public string NumberMaterial { get; set; }
        public string Name { get; set; }
        public int EdIzmID { get; set; }
        public string Ostat { get; set; }
        public int WarehouseID { get; set; }
    
        public virtual EdIzm EdIzm { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
